function createrectangle(figure1)
%CREATERECTANGLE(FIGURE1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 20-Aug-2013 10:07:18

% Create rectangle
annotation(figure1,'rectangle',...
    'Position',[1.54,3,0.07,5],...
    'FaceAlpha',0.5,...
    'FaceColor',[0.3 0.3 0.3]);
end

